/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category { 'id' : bigint, 'name' : string }
export interface Product {
  'id' : bigint,
  'name' : string,
  'category' : string,
  'price' : bigint,
}
export interface _SERVICE {
  'addCategory' : ActorMethod<
    [string, string],
    { 'ok' : Category } |
      { 'err' : string }
  >,
  'addProduct' : ActorMethod<
    [string, bigint, string, string],
    { 'ok' : Product } |
      { 'err' : string }
  >,
  'deleteCategory' : ActorMethod<
    [bigint, string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'deleteProduct' : ActorMethod<
    [bigint, string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'getCategory' : ActorMethod<[bigint], [] | [Category]>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'listCategories' : ActorMethod<[], Array<Category>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'updateProduct' : ActorMethod<
    [bigint, string, bigint, string, string],
    { 'ok' : Product } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];